### ISSUE TITLE
Καλησπέρα καλή χρονιά

### ISSUE THREAD

**Issue by ghost** [kala2/react-hooks-tailwind-crud#1]
Δυστυχώς δεν κατάφερα να εγκαταστήσω την εφαρμογή σας.

Ευχαριστώ

**Comment by kala2** [comment]
Καλησπέρα,

Τι node, tsc version εχεις; 
Δοκίμασε με:

node >= 12.5.0
tsc >= 3.6.4

**Comment by ghost** [comment]
Καλησπέρα, δοκίμασα με τις εκδόσεις που σύστησες και δούλεψε. Ευχαριστώ!
